### ISSUE TITLE
实验中的训练人脸高低分辨率和对比算法训练相关问题？

### ISSUE THREAD

**Issue by kingseeking** [HaoHou-98/SCGAN#1]
今天在arxiv看到大神这篇文章，非常值得学习。文章中除了Fig.1展示说低高分辨率分别是16,64,实验训练中没有提起。从实验展示的图片质量来看，感觉分辨率不是很高。假设实验中的高分辨率为64的话，产生了另外一个问题：如果在高分辨率为64的x4倍进行超分对比方法实验，请问如何对DFDNet,CFPGAN,HifaceGAN这样的原始高分辨率为512的算法进行训练，或者如何跟这些算法进行比较的。

期待大神的回复。

另外，我发现4.1节中合成退化模型可能有个编辑错误，应该是LrL->LrH。

**Comment by neverwinHao** [comment]
> 今天在arxiv看到大神这篇文章，非常值得学习。文章中除了Fig.1展示说低高分辨率分别是16,64,实验训练中没有提起。从实验展示的图片质量来看，感觉分辨率不是很高。假设实验中的高分辨率为64的话，产生了另外一个问题：如果在高分辨率为64的x4倍进行超分对比方法实验，请问如何对DFDNet,CFPGAN,HifaceGAN这样的原始高分辨率为512的算法进行训练，或者如何跟这些算法进行比较的。
> 
> 期待大神的回复。
> 
> 另外，我发现4.1节中合成退化模型可能有个编辑错误，应该是LrL->LrH。

我也有相同的困惑，请问您解决了吗？
