### ISSUE TITLE
Key error while loading pretrained model

### ISSUE THREAD

**Issue by FlowDownTheRiver** [HaoHou-98/SCGAN#3]
My env : 
#
# Name                    Version                   Build  Channel
ca-certificates           2022.4.26            haa95532_0
certifi                   2022.5.18.1      py37haa95532_0
cudatoolkit               10.2.89              h74a9793_1
openssl                   1.1.1o               h2bbff1b_0
pip                       21.2.4           py37haa95532_0
python                    3.7.13               h6244533_0
setuptools                61.2.0           py37haa95532_0
sqlite                    3.38.3               h2bbff1b_0
torch                     1.11.0+cu113             pypi_0    pypi
torchaudio                0.11.0+cu113             pypi_0    pypi
torchvision               0.12.0+cu113             pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py37haa95532_2

----------------------------------------------------------------------------------------------------------------------------------

This is the error : 

Traceback (most recent call last):
  File "test.py", line 58, in <module>
    main()
  File "test.py", line 35, in main
    a = torch.load('./pretrained_model/pretrained_model.pth')["G_RLS"]
KeyError: 'G_RLS'

I have tried it with pytorch cuda 10.2 and cuda 11.3 just in case if that fixes the error or not,but no chance.

A solution please?

**Comment by lmvgjp** [comment]
hello,
i have the same problem...did you solve it?
also I tried to train the method but it looks like it needs as input small 64x64 patches...is it true?
thanks

**Comment by hamedsteiner** [comment]
Does this change in test.py fix your error?

Based on the code base, I guess the problem is with Gh2l (High-res to low-res)
`a = torch.load('./pretrained_model/pretrained_model.pth')["G_h2l"]`, which should be changed to 
`b = torch.load('./pretrained_model/pretrained_model.pth')["G_l2h"]`.
Prior to that I though the problem is with mu cuda version, etc.

**Comment by HaoHou-98** [comment]
> Does this change in test.py fix your error?
> 
> Based on the code base, I guess the problem is with Gh2l (High-res to low-res) `a = torch.load('./pretrained_model/pretrained_model.pth')["G_h2l"]`, which should be changed to `b = torch.load('./pretrained_model/pretrained_model.pth')["G_l2h"]`. Prior to that I though the problem is with mu cuda version, etc.

Thank you for the solution, and I will explain it in the README.md.
