### ISSUE TITLE
Weights of the model trained by myself can not be used in 'test.py'

### ISSUE THREAD

**Issue by han265** [HaoHou-98/SCGAN#7]
Hello, thanks for your great work at first!
I 'm trying to reproduce the results in the paper. However, when I use the weights of the model trained by myself, it reports the error as follows:

Traceback (most recent call last):
  File "test.py", line 59, in <module>
    main()
  File "test.py", line 35, in main
    a = torch.load('./pretrained_model_self/pretrained_model.pth')["G_l2h"]
KeyError: 'G_l2h'

I' d like to know what caused that. Thank you very much!

**Comment by han265** [comment]
I have solved it.

**Comment by HaoHou-98** [comment]
> I have solved it.

Sorry for not seeing your email in time, the key saved by the model I trained before posting the code to github is "G_l2h", however the key saved by the training code I posted to github is "G_RLS", which is due to the fact that I rearranged the code to correspond to the content of this paper.

**Comment by han265** [comment]
> > I have solved it.
> 
> Sorry for not seeing your email in time, the key saved by the model I trained before posting the code to github is "G_l2h", however the key saved by the training code I posted to github is "G_RLS", which is due to the fact that I rearranged the code to correspond to the content of this paper.

That's all right. Thanks for your explanation very much. 
I've met a new problem. I searched for some official or unofficial code to calculate the metric value(FID, KID, LPIPS, NIQE) mentioned in the paper, but most of them are not suitable for the size of output images(64*64). So could you please share your corresponding code with me? You can send it to my email(s_han@stu.xidian.edu.cn) if possible. Thanks a lot!

**Comment by HaoHou-98** [comment]
Hi, all metrics are calculated by the official code or Matlab built-in functions. For FID and KID scores, you can use this code to do the calculation https://github.com/toshas/torch-fidelity
