### ISSUE TITLE
can you share the high-resolution about ls3d_w and ffhq in test dataset, or the code to generate low-resolution sample

### ISSUE THREAD

**Issue by kingseeking** [HaoHou-98/SCGAN#8]
Hi, Nice work! We want to you model to evalutate the LPIPS PSNR SSIM. But the high-resolution of ls3d-W and ffhq are absent. 

we use your describe the method and the param in paper to generate low-resolution sample, the result is abnormal. But we use your public test data can work well. The result as follow:
![image](https://user-images.githubusercontent.com/31261122/223602993-d332477c-592e-4dad-88b5-983c47f5adac.png)
the top are the result of the public test ffhq; the bottom are the result our generated samples.

can you share the high-resolution about ls3d_w and ffhq in test dataset, or the code to generate low-resolution sample. Thanks.
my email: 1375278373@qq.com

**Comment by HaoHou-98** [comment]
Hello, the LS3D-W balanced test set used in the paper is obtained by a simple down-sampling operation, the degradation method used in the FFHQ test set is also described in the paper, but as shown in the figure, Your test data seems to be suffering from more severe degradation. The public test data is obtained through the face detector detection and cropping, in fact, we found in the test, the proportion of human face in the face image is important, which may have a significant impact on the performance of the model, and we are actively exploring the corresponding solutions.  I will send you the corresponding high-resolution images when I have time, sorry for the delay.

**Comment by kingseeking** [comment]
> Hello, the LS3D-W balanced test set used in the paper is obtained by a simple down-sampling operation, the degradation method used in the FFHQ test set is also described in the paper, but as shown in the figure, Your test data seems to be suffering from more severe degradation. The public test data is obtained through the face detector detection and cropping, in fact, we found in the test, the proportion of human face in the face image is important, which may have a significant impact on the performance of the model, and we are actively exploring the corresponding solutions. I will send you the corresponding high-resolution images when I have time, sorry for the delay.

thanks for your reply，Look forward to your sharing soon！

**Comment by han48614284** [comment]
> [1375278373](mailto:1375278373@qq.com)

Could you please send one copy to me, too?  E-Mail: s_han@stu.xidian.edu.cn@qq.com

**Comment by han48614284** [comment]
Could you please send one copy to me, too? E-Mail: s_han@stu.xidian.edu.cn

**Comment by willswordh** [comment]
@HaoHou-98 Great work! any update on the best proportion of human face in the face image? Thanks!
